language: python

sudo: false

env:
  global:
  - CITRINATION_API_KEY=IeReqZ4bK4TS1jjbg3q2zAtt
  - CITRINATION_SITE=https://stage.citrination.com

python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'

install:
- pip install pytest
- python setup.py install

script:
- py.test citrination_client --verbose

deploy:
  provider: pypi
  user: CitrineInformatics
  password:
    secure: QZzjzmvHPNU3+EQ7QIxb07awb2frB2g2TQHJN8v2HRyIP8KHqxmJksdQuAUfzoj/7QyPWTLXtfV032eQbqliFnc8LfxZtVgIh2f5ThX1SqgmxvDMugldOKI9jEzEjtkK5imuQ3LMEsnDugmTeqz/T/8y7xkM+16JFyOeJ1yAYnS28i8KwJpg0Dq4v6WMm+iKWK5vwoLpiRYGUZRqleGLTY/nvrQfJJh3y1aKNKFYBdEBp68AGWZ0K5WEGaIeImsmmglVm8J2RJ80RgSRk3DVM13pyXrVL1hixJWw2LiLoEyUhmiCXBKNZPOZ+uUw3PeGNHKJRPbeF8uoi0rclaNSrliYt2T+uZNZN7Ct6ff9KX0RDtqRAUmaocLB0DxNHZUmehfLGmEGjnXl9zXn5lO1F64DErUanMVkwuzdhpsdthfPV/n8xqQAuPRzS9EijD/9gg7K2D3IhItOO3Yd3FvfzEFU/NcM2WdR8V1QqPbzrk1Q6SsFibtjMkJCLUY6YTGBA4ChQi2Sc2ec8B/982ZNkCH9gbFiK3nljlUep3nCFLy/ZvW5o+JRzXEE29LiTjh4eHwG99YPAECmsR68X/cQAcViIXj/BiWVTDSn5uCVymEij9BMRf64D6srbhU3X7up14nXt4LC8wwm47O6+oALX4mYZsyu61ZER81G040Qm/Q=
  on:
    distributions: sdist bdist_wheel
    repo: CitrineInformatics/python-citrination-client
    branch: master
