language: python
env:
  global:
  - CITRINATION_SITE=https://citrination.com
  - secure: qcH/fSQwZf+GDM0HVm8j8kKTgYljNxkFogyI56s1kv8sB9FFpg8GVncf+ot8IT743YFr4TP/csofwFApo/yBu4fcIzy83zXXaJ0SbRDAEObLiHrT4WLhw7DjzmXIt0EIw1q6VPrMcrDaP6KbEWBZC+Yt72Hv4g4EO0l6BdLhRyeHamlAosFjCeI7H2+B3FX8UnJEvsBQSI3Qc2u//sYFq9lYmDFKsO5Wze25CGULWlOSHwbO9g5tzGDQOmJQHCk3qJZxANM+CD/xeGJz0G26tXB0JXcvZLPskoWjtN3GNYPgbUlwV/oquYwPuB3wkpZHmrQ2Fb1wJ6Fl52JPNeeV6FXfNW2PtmlLHuymrszfw1pavnpkKCPPZUFGZbmb2yjSGVLIym+wWsxzAuOLiWU7R57lCSVmN2nyMvr4FqM/ljiT3sJo26/FVBeui8pMmTxYa/8Hm9kun2jXwBLxiP14FSo4rc/jM6I5OeXwNq3rT005ZVrRCSVUSvXAOHhovYpuE2kibsHW8Vn1gmxB1I3RWFCKr658tgleUgi6R+WvtDH+rZ3B77Nop4t5ojVK8jplIgBBs85pF/TBoz+r0lWLKyWMZpaBLfHHpoILraWTar9HCzR8T3n/izRVMYuw45DkrtgMe1o1cjpPJNBCncVpx65elgwRcYRk16xwL6kLp/w=
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install pytest
- pip install requests_mock
- python setup.py install
script:
- py.test citrination_client --verbose
deploy:
  provider: pypi
  user: CitrineInformatics
  password:
    secure: YER1lIwYpEBLCtLssBF+CW/lCfAblkBBDtHC7ESCNr6sQwEKHTbF7ihvxyld55Y9DmnTXssFYLShFOvC5CZ7A+b7LZMmFdGc5f2n0X+6FA+paOJ5+6BXzFaP3X84XQsvy7wluz0f58roQq+o//8I+d5WPrrKczmNJUyAq7V74AhWdgpITgnBlomyNUS01HxX9qMDw1eVKOQv2Qccs+xgwkWPtlQw542oMHFb0SwRPSWm0GMY2ykyT4CehOLZqkye0EKs5K75BFtlTtXUjT+bPEfHoYk4kJmcb4wiSisXuLCt4eJcSYiBB7bOTZLC/DmNLMeakknIBQ14cRACcJ+0gcLX0sNPt/BZrcdJhUeYtRc/CLYHYv8m42KhtLicU/K6907HlDf1/KmJhhn2B/sOf7XKyP3ztxJnR/ZXEbSsgtWSY4+W6KKW3kWcyyabfCDp3lZYlKG3I+13MYDooaL4p/h8knjBx6dgOCS9Jbr99IvAA3u/aRFCayseCqEtIFjJF4WbR7rySbPHwL5WremmlDi+SZpe143ALZyqNTVP89k14sztARntkbCqrY9QTw5KYSFxPMr3RETz+3q4PI9i4fYOO6XCU0wWJnL3cYxLRh7bj0mRk76lsGD9o3ZLWyQud7zWtsz+TPHUAUvuHYYsFHUgID768UngKs/59JcELFA=
  on:
    python: '3.6'
    distributions: sdist bdist_wheel
    repo: CitrineInformatics/python-citrination-client
    branch: master
