language: python
env:
  global:
  - CITRINATION_SITE=https://citrination.com
  - secure: ooNMjc4NNcadowzCSogXA6sFgCBdN/REFMR0utjGt1gr42cOQyBqJu0AjWlFvWzE1amGArvaijhyqKA6xCCxHa67FgMHTOh5zi7Z3HiAA7kXKt3tI+A6ggWuMMveqUbsf8IU50mWyTXPCRdSc/F2SMv2WFxWK+wpsNSg64g68cLPFc8e7+Aqc92weOUtn2J0oht2IZDB/W0JY4bnhSt0+76IJhgR+vsz1ERQGPiZuTIu/3ZxWtcdl7sdQM79K7Xu6jDMrN18hJWZqnMnisltTdbU7RtiHAizksEVFLxQkB2sjRkGVsJ6c3UkA6JtHv+GVhYIbv3vVK52Q2PrFuzqxdtfRQbmZc2+E2BrTt6XLK8Wa3MKJMlWCI/Xe+cjFBlemBCDCcqTUPnBBGEf3zBjCF0UUmcGu0JBDyFfYkPwp1b7OeDn7L/+RG/g2+4yEu2VlOHwUtzwimpKbcA+dWNs+Mk5r4RE+1ZVnMNuTOjGdFfLQqDqEYM1C2Hd37zebTVW6wYgyec4cysmsxqyPJAKRFfQ37nVWDd41jZGtyCEAiWuG2LrYtxy5hSChXXYOTSvYsJt7TsklBgEAndJaQ/W4lW7JKtwJRCxmzOgwIgVsZmxMsKsM9kRVfJpzCpya7F6iwEYgbxn2F/vVzS+1qgi3miXy+jL/6e+0DbiS32fQWM=
  matrix:
    secure: ppEWCs94IRGl1Cp2WYCcWLl69AwOhfQXDTeq/yQk6wHtPpyBq1EfC5qrPHWLuNYrBkStU4ZfwDmEKww0NrO778eJP82aJ1uuofFfWsnbxFV1XrNTz93bDvv9ecnA72UBna/I3+wAHvu36kWFxqsRqqcgBeJrJoygcysf99dnI46nyp5qegi/aDzeox6B4oUUKSWEQsYu+r8P1WtuJ94hiGNJoOWzs2jY48k6f37k5eHCOaXlHIa+O41Yb/S7XpSh8MlKKguAo5mEqOZxewqIg8gbR76K1k++fcmPSezJG6AYKVVu/J/pzgNWHVv5yCf9sOuiY8gdioQANh/znKmsHbjMqPFUwIAg/Lqaa04qbPtUzofFGWetIJxDvnS3kcQOWNTQ57686MNUgOvfJUQCm3lrCR5rwqskmerQzzRC/j7oE6n54eYJ/FnifgGtqF3ATpCuMxanUi3gr5fyhf12SyMOQUOlRCJPOCk9cUwxJ2L9uRPlNtUGPqR/iLY8CqDuH9xsIAhtNe2MLRNyFtk95PJZ1/W0dhrQY55kEDLc0PgsTEJJgW6pCtZyop3jPSNRJrcnPnr0YzvBg0ianYVBQJ02antmF954Q78NGNLi4ILiKkWx1F/cq/MlykML/1VUjPVYCKfN0yGv7reM9qLs6w9Yo0Z9TMCD6wboBNSeSh0=
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install pytest
- python setup.py install
script:
- py.test citrination_client --verbose
deploy:
  provider: pypi
  user: CitrineInformatics
  password:
    secure: YER1lIwYpEBLCtLssBF+CW/lCfAblkBBDtHC7ESCNr6sQwEKHTbF7ihvxyld55Y9DmnTXssFYLShFOvC5CZ7A+b7LZMmFdGc5f2n0X+6FA+paOJ5+6BXzFaP3X84XQsvy7wluz0f58roQq+o//8I+d5WPrrKczmNJUyAq7V74AhWdgpITgnBlomyNUS01HxX9qMDw1eVKOQv2Qccs+xgwkWPtlQw542oMHFb0SwRPSWm0GMY2ykyT4CehOLZqkye0EKs5K75BFtlTtXUjT+bPEfHoYk4kJmcb4wiSisXuLCt4eJcSYiBB7bOTZLC/DmNLMeakknIBQ14cRACcJ+0gcLX0sNPt/BZrcdJhUeYtRc/CLYHYv8m42KhtLicU/K6907HlDf1/KmJhhn2B/sOf7XKyP3ztxJnR/ZXEbSsgtWSY4+W6KKW3kWcyyabfCDp3lZYlKG3I+13MYDooaL4p/h8knjBx6dgOCS9Jbr99IvAA3u/aRFCayseCqEtIFjJF4WbR7rySbPHwL5WremmlDi+SZpe143ALZyqNTVP89k14sztARntkbCqrY9QTw5KYSFxPMr3RETz+3q4PI9i4fYOO6XCU0wWJnL3cYxLRh7bj0mRk76lsGD9o3ZLWyQud7zWtsz+TPHUAUvuHYYsFHUgID768UngKs/59JcELFA=
  on:
    distributions: sdist bdist_wheel
    repo: CitrineInformatics/python-citrination-client
    branch: master
