language: python

sudo: false

env:
  - CITRINATION_API_KEY=IeReqZ4bK4TS1jjbg3q2zAtt
  - CITRINATION_SITE=https://stage.citrination.com

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install pytest
  - python setup.py install

script:
  - py.test python-citrination-client --verbose
